[2025-04-15T07:27:58.857+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-15T07:27:58.897+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_advanced.test.dbt_lewagon.not_null_my_first_dbt_model_id scheduled__2025-04-14T00:00:00+00:00 [queued]>
[2025-04-15T07:27:58.912+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_advanced.test.dbt_lewagon.not_null_my_first_dbt_model_id scheduled__2025-04-14T00:00:00+00:00 [queued]>
[2025-04-15T07:27:58.913+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-04-15T07:27:58.933+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): test.dbt_lewagon.not_null_my_first_dbt_model_id> on 2025-04-14 00:00:00+00:00
[2025-04-15T07:27:58.946+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_advanced', 'test.dbt_lewagon.not_null_my_first_dbt_model_id', 'scheduled__2025-04-14T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/advanced/dbt_advanced.py', '--cfg-path', '/tmp/tmp0xz38koh']
[2025-04-15T07:27:58.948+0000] {standard_task_runner.py:105} INFO - Job 13: Subtask test.dbt_lewagon.not_null_my_first_dbt_model_id
[2025-04-15T07:27:58.953+0000] {logging_mixin.py:190} WARNING - /root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1344) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-15T07:27:58.954+0000] {standard_task_runner.py:72} INFO - Started process 1347 to run task
[2025-04-15T07:27:59.054+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt_advanced.test.dbt_lewagon.not_null_my_first_dbt_model_id scheduled__2025-04-14T00:00:00+00:00 [running]> on host 9a8ef20dd1da
[2025-04-15T07:27:59.199+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dbt_advanced' AIRFLOW_CTX_TASK_ID='test.dbt_lewagon.not_null_my_first_dbt_model_id' AIRFLOW_CTX_EXECUTION_DATE='2025-04-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-14T00:00:00+00:00'
[2025-04-15T07:27:59.200+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-15T07:27:59.228+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-15T07:27:59.229+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt test --models not_null_my_first_dbt_model_id --project-dir /app/airflow/dbt_lewagon']
[2025-04-15T07:27:59.245+0000] {subprocess.py:99} INFO - Output:
[2025-04-15T07:28:02.464+0000] {subprocess.py:106} INFO - [0m07:28:02  Running with dbt=1.9.1
[2025-04-15T07:28:04.585+0000] {subprocess.py:106} INFO - [0m07:28:04  Registered adapter: bigquery=1.9.0
[2025-04-15T07:28:05.757+0000] {subprocess.py:106} INFO - [0m07:28:05  Found 2 models, 4 data tests, 489 macros
[2025-04-15T07:28:05.759+0000] {subprocess.py:106} INFO - [0m07:28:05
[2025-04-15T07:28:05.761+0000] {subprocess.py:106} INFO - [0m07:28:05  Concurrency: 1 threads (target='dev')
[2025-04-15T07:28:05.763+0000] {subprocess.py:106} INFO - [0m07:28:05
[2025-04-15T07:28:06.345+0000] {subprocess.py:106} INFO - [0m07:28:06  1 of 1 START test not_null_my_first_dbt_model_id ............................... [RUN]
[2025-04-15T07:28:08.435+0000] {subprocess.py:106} INFO - [0m07:28:08  1 of 1 FAIL 1 not_null_my_first_dbt_model_id ................................... [[31mFAIL 1[0m in 2.09s]
[2025-04-15T07:28:08.495+0000] {subprocess.py:106} INFO - [0m07:28:08
[2025-04-15T07:28:08.495+0000] {subprocess.py:106} INFO - [0m07:28:08  Finished running 1 test in 0 hours 0 minutes and 2.73 seconds (2.73s).
[2025-04-15T07:28:08.682+0000] {subprocess.py:106} INFO - [0m07:28:08
[2025-04-15T07:28:08.683+0000] {subprocess.py:106} INFO - [0m07:28:08  [31mCompleted with 1 error, 0 partial successes, and 0 warnings:[0m
[2025-04-15T07:28:08.684+0000] {subprocess.py:106} INFO - [0m07:28:08
[2025-04-15T07:28:08.685+0000] {subprocess.py:106} INFO - [0m07:28:08  [31mFailure in test not_null_my_first_dbt_model_id (models/example/schema.yml)[0m
[2025-04-15T07:28:08.686+0000] {subprocess.py:106} INFO - [0m07:28:08    Got 1 result, configured to fail if != 0
[2025-04-15T07:28:08.687+0000] {subprocess.py:106} INFO - [0m07:28:08
[2025-04-15T07:28:08.688+0000] {subprocess.py:106} INFO - [0m07:28:08    compiled code at target/compiled/dbt_lewagon/models/example/schema.yml/not_null_my_first_dbt_model_id.sql
[2025-04-15T07:28:08.689+0000] {subprocess.py:106} INFO - [0m07:28:08
[2025-04-15T07:28:08.690+0000] {subprocess.py:106} INFO - [0m07:28:08  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2025-04-15T07:28:09.989+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-04-15T07:28:10.017+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-15T07:28:10.024+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dbt_advanced, task_id=test.dbt_lewagon.not_null_my_first_dbt_model_id, run_id=scheduled__2025-04-14T00:00:00+00:00, execution_date=20250414T000000, start_date=20250415T072758, end_date=20250415T072810
[2025-04-15T07:28:10.041+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-15T07:28:10.042+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 13 for task test.dbt_lewagon.not_null_my_first_dbt_model_id (Bash command failed. The command returned a non-zero exit code 1.; 1347)
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-15T07:28:10.078+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-15T07:28:10.110+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-15T07:28:10.111+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
